---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.20.3

platforms:
  - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[nagios_v_shell_test::default]
      - recipe[nagios_v_shell::default]
